version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/usvc/go-config
    versions:
    - 0.2.3
    - 0.2.4
    - 0.2.5
    - 0.2.6
  - dependency-name: github.com/spf13/cobra
    versions:
    - 0.0.7
